version: 2.1

executors:
  docker:
    environment:
      IMAGE_NAME: gerritk/ytt
    docker:
      - image: docker:18.06.3-ce-git

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            YTT_VERSION=${CIRCLE_TAG:-develop}

            docker build \
                --label org.label-schema.build-date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
                --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
                --label org.label-schema.vcs-url="https://github.com/Gerrit-K/ytt-docker" \
                --label org.label-schema.version="${YTT_VERSION}" \
                --label org.label-schema.schema-version="1.0" \
                --build-arg YTT_VERSION="${YTT_VERSION}" \
                -t ${IMAGE_NAME}:latest \
                .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar ${IMAGE_NAME}
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  push:
    executor: docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Push Docker image
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login -u ${DOCKERHUB_USERNAME} --password-stdin

            TAG=${CIRCLE_TAG:-${CIRCLE_BRANCH:-unknown}}
            docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${TAG}

            docker push ${IMAGE_NAME}:latest
            docker push ${IMAGE_NAME}:${TAG}

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - push:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
          context: Docker Hub
